name: Testing and Coverage

on:
  push:
    branches: ["main"]
    paths:
      - "niveshpy/**"
      - "tests/**"
      - ".github/workflows/test.yml"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test and build coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          # Install a specific version of uv.
          version: "0.11.3"
          enable-cache: true

      - name: Install python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest
          mv .coverage .coverage.${{ matrix.python-version }} # Rename coverage file for clarity

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-data-${{ matrix.python-version }}
          path: .coverage.*
          include-hidden-files: true
          if-no-files-found: ignore

  coverage:
    name: Combine and check coverage
    runs-on: ubuntu-latest
    needs: test
    if: always() # Ensure this job runs even if the test job fails
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.11.3"
          enable-cache: true

      - name: Install python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Download coverage data
        uses: actions/download-artifact@v8
        with:
          pattern: coverage-data-*
          merge-multiple: true

      - name: Combine coverage data and generate report
        run: |
          uv run coverage combine # Combine all .coverage files
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY # Output to GitHub summary
          uv run coverage html --skip-covered --skip-empty --fail-under 80 # Generate HTML report for detailed view

      - name: Upload HTML coverage report
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html-report
          path: htmlcov
